export const OPERATOR_PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_PROPERTIES: 'VIEW_PROPERTIES',
  EDIT_PROPERTIES: 'EDIT_PROPERTIES',
  CREATE_PROPERTIES: 'CREATE_PROPERTIES',
  ARCHIVE_PROPERTIES: 'ARCHIVE_PROPERTIES',
  MANAGE_PROPERTY_DOCUMENTS: 'MANAGE_PROPERTY_DOCUMENTS',
  NOTIFY_PROPERTY_INVESTORS: 'NOTIFY_PROPERTY_INVESTORS',
  MANAGE_PROPERTY_TYPES: 'MANAGE_PROPERTY_TYPES',
  VIEW_INVESTORS: 'VIEW_INVESTORS',
  EDIT_INVESTORS: 'EDIT_INVESTORS',
  REVIEW_INVESTOR_ACCOUNTS: 'REVIEW_INVESTOR_ACCOUNTS',
  REVIEW_ACCREDITATION: 'REVIEW_ACCREDITATION',
  MANAGE_INVESTMENT_REQUESTS: 'MANAGE_INVESTMENT_REQUESTS',
  VIEW_FINANCIAL_ACTIVITY: 'VIEW_FINANCIAL_ACTIVITY',
  REVIEW_DEPOSITS: 'REVIEW_DEPOSITS',
  MANAGE_CONTRIBUTIONS: 'MANAGE_CONTRIBUTIONS',
  MANAGE_RETURN_DISTRIBUTIONS: 'MANAGE_RETURN_DISTRIBUTIONS',
  REVIEW_CASH_OUTS: 'REVIEW_CASH_OUTS',
  REVIEW_REINVESTMENTS: 'REVIEW_REINVESTMENTS',
  EDIT_WEBSITE_CONTENT: 'EDIT_WEBSITE_CONTENT',
  VIEW_TECHNICAL_DATA: 'VIEW_TECHNICAL_DATA',
}

export const DEFAULT_OPERATOR_PERMISSIONS = [
  OPERATOR_PERMISSIONS.VIEW_DASHBOARD,
  OPERATOR_PERMISSIONS.VIEW_PROPERTIES,
  OPERATOR_PERMISSIONS.EDIT_PROPERTIES,
  OPERATOR_PERMISSIONS.MANAGE_PROPERTY_DOCUMENTS,
  OPERATOR_PERMISSIONS.VIEW_INVESTORS,
  OPERATOR_PERMISSIONS.REVIEW_INVESTOR_ACCOUNTS,
  OPERATOR_PERMISSIONS.REVIEW_ACCREDITATION,
  OPERATOR_PERMISSIONS.MANAGE_INVESTMENT_REQUESTS,
  OPERATOR_PERMISSIONS.VIEW_FINANCIAL_ACTIVITY,
]

export const OPERATOR_PERMISSION_GROUPS = [
  { id: 'dashboard', permissions: [OPERATOR_PERMISSIONS.VIEW_DASHBOARD] },
  {
    id: 'properties',
    permissions: [
      OPERATOR_PERMISSIONS.VIEW_PROPERTIES,
      OPERATOR_PERMISSIONS.EDIT_PROPERTIES,
      OPERATOR_PERMISSIONS.CREATE_PROPERTIES,
      OPERATOR_PERMISSIONS.ARCHIVE_PROPERTIES,
      OPERATOR_PERMISSIONS.MANAGE_PROPERTY_DOCUMENTS,
      OPERATOR_PERMISSIONS.NOTIFY_PROPERTY_INVESTORS,
      OPERATOR_PERMISSIONS.MANAGE_PROPERTY_TYPES,
    ],
  },
  {
    id: 'investors',
    permissions: [
      OPERATOR_PERMISSIONS.VIEW_INVESTORS,
      OPERATOR_PERMISSIONS.EDIT_INVESTORS,
      OPERATOR_PERMISSIONS.REVIEW_INVESTOR_ACCOUNTS,
      OPERATOR_PERMISSIONS.REVIEW_ACCREDITATION,
    ],
  },
  { id: 'investments', permissions: [OPERATOR_PERMISSIONS.MANAGE_INVESTMENT_REQUESTS] },
  {
    id: 'finance',
    permissions: [
      OPERATOR_PERMISSIONS.VIEW_FINANCIAL_ACTIVITY,
      OPERATOR_PERMISSIONS.REVIEW_DEPOSITS,
      OPERATOR_PERMISSIONS.MANAGE_CONTRIBUTIONS,
      OPERATOR_PERMISSIONS.MANAGE_RETURN_DISTRIBUTIONS,
      OPERATOR_PERMISSIONS.REVIEW_CASH_OUTS,
      OPERATOR_PERMISSIONS.REVIEW_REINVESTMENTS,
    ],
  },
  { id: 'content', permissions: [OPERATOR_PERMISSIONS.EDIT_WEBSITE_CONTENT] },
  { id: 'technical', permissions: [OPERATOR_PERMISSIONS.VIEW_TECHNICAL_DATA] },
]

const VALID_PERMISSIONS = new Set(Object.values(OPERATOR_PERMISSIONS))

export function normalizeOperatorPermissions(value) {
  const permissions = Array.isArray(value) ? value.filter((item) => VALID_PERMISSIONS.has(item)) : []
  const unique = [...new Set(permissions)]
  if (unique.includes(OPERATOR_PERMISSIONS.NOTIFY_PROPERTY_INVESTORS)) {
    if (!unique.includes(OPERATOR_PERMISSIONS.MANAGE_PROPERTY_DOCUMENTS)) {
      unique.push(OPERATOR_PERMISSIONS.MANAGE_PROPERTY_DOCUMENTS)
    }
  }
  return unique
}

export function hasOperatorPermission(user, permission) {
  if (user?.type === 'ADMIN') return true
  return user?.type === 'OPERATOR' && normalizeOperatorPermissions(user.operatorPermissions).includes(permission)
}

export function isAdminActor(user) {
  return user?.type === 'ADMIN' || user?.type === 'OPERATOR'
}

