import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { getServerSession } from "next-auth"
import { Viewport } from 'next'

import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

import SessionProvider from "../components/SessionProvider"
import NavMenu from "../components/NavMenu"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Golden State - Capital Investment",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
}

export const viewport = {
  width: 'device-width',
  initialScale: 1
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params
  const session = await getServerSession()

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <NextIntlClientProvider locale={locale}>
            <main>
              <NavMenu/>
              <div id="content" style={{ marginTop: '76px' }}>
                {children}
              </div>
            </main>
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
