import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { getServerSession } from "next-auth"
import { authOptions } from '@/app/api/auth/[...nextauth]/route'

import "./globals.css"

import SessionProvider from "../components/SessionProvider"
import NavMenuServer from "../components/NavMenuServer"
import Footer from "../components/Footer"

export const metadata = {
  title: "Golden State - Capital Investment",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
}

export const viewport = {
  width: 'device-width',
  initialScale: 1
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params
  const session = await getServerSession(authOptions)

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body className="antialiased">
        <SessionProvider session={session}>
          <NextIntlClientProvider locale={locale}>
            <main>
              <NavMenuServer session={session} />
              <div id="content" className="mt-[76px]">
                {children}
              </div>
              <Footer />
            </main>
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
